# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: heart.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='heart.proto',
  package='Pbheart',
  syntax='proto2',
  serialized_pb=_b('\n\x0bheart.proto\x12\x07Pbheart\"\x19\n\x08HeartReq\x12\r\n\x05heart\x18\x01 \x01(\t\"(\n\tHeartResp\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\r\n\x05token\x18\x02 \x01(\t')
)




_HEARTREQ = _descriptor.Descriptor(
  name='HeartReq',
  full_name='Pbheart.HeartReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='heart', full_name='Pbheart.HeartReq.heart', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=49,
)


_HEARTRESP = _descriptor.Descriptor(
  name='HeartResp',
  full_name='Pbheart.HeartResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='Pbheart.HeartResp.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='token', full_name='Pbheart.HeartResp.token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=91,
)

DESCRIPTOR.message_types_by_name['HeartReq'] = _HEARTREQ
DESCRIPTOR.message_types_by_name['HeartResp'] = _HEARTRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HeartReq = _reflection.GeneratedProtocolMessageType('HeartReq', (_message.Message,), dict(
  DESCRIPTOR = _HEARTREQ,
  __module__ = 'heart_pb2'
  # @@protoc_insertion_point(class_scope:Pbheart.HeartReq)
  ))
_sym_db.RegisterMessage(HeartReq)

HeartResp = _reflection.GeneratedProtocolMessageType('HeartResp', (_message.Message,), dict(
  DESCRIPTOR = _HEARTRESP,
  __module__ = 'heart_pb2'
  # @@protoc_insertion_point(class_scope:Pbheart.HeartResp)
  ))
_sym_db.RegisterMessage(HeartResp)


# @@protoc_insertion_point(module_scope)
