# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: socket.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='socket.proto',
  package='socket_rpc',
  syntax='proto2',
  serialized_pb=_b('\n\x0csocket.proto\x12\nsocket_rpc\"?\n\x06RpcReq\x12\x0b\n\x03rpc\x18\x01 \x02(\t\x12\x0c\n\x04\x62ody\x18\x02 \x02(\x0c\x12\r\n\x05token\x18\x03 \x02(\t\x12\x0b\n\x03\x65xt\x18\x04 \x02(\t\"M\n\x06RpcRsp\x12\x0b\n\x03rpc\x18\x01 \x02(\t\x12\x0c\n\x04\x62ody\x18\x02 \x02(\x0c\x12\r\n\x05token\x18\x03 \x02(\t\x12\x0b\n\x03\x65xt\x18\x04 \x02(\t\x12\x0c\n\x04\x63ode\x18\x05 \x02(\x05')
)




_RPCREQ = _descriptor.Descriptor(
  name='RpcReq',
  full_name='socket_rpc.RpcReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rpc', full_name='socket_rpc.RpcReq.rpc', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='body', full_name='socket_rpc.RpcReq.body', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='token', full_name='socket_rpc.RpcReq.token', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ext', full_name='socket_rpc.RpcReq.ext', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=91,
)


_RPCRSP = _descriptor.Descriptor(
  name='RpcRsp',
  full_name='socket_rpc.RpcRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rpc', full_name='socket_rpc.RpcRsp.rpc', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='body', full_name='socket_rpc.RpcRsp.body', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='token', full_name='socket_rpc.RpcRsp.token', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ext', full_name='socket_rpc.RpcRsp.ext', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='code', full_name='socket_rpc.RpcRsp.code', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=170,
)

DESCRIPTOR.message_types_by_name['RpcReq'] = _RPCREQ
DESCRIPTOR.message_types_by_name['RpcRsp'] = _RPCRSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RpcReq = _reflection.GeneratedProtocolMessageType('RpcReq', (_message.Message,), dict(
  DESCRIPTOR = _RPCREQ,
  __module__ = 'socket_pb2'
  # @@protoc_insertion_point(class_scope:socket_rpc.RpcReq)
  ))
_sym_db.RegisterMessage(RpcReq)

RpcRsp = _reflection.GeneratedProtocolMessageType('RpcRsp', (_message.Message,), dict(
  DESCRIPTOR = _RPCRSP,
  __module__ = 'socket_pb2'
  # @@protoc_insertion_point(class_scope:socket_rpc.RpcRsp)
  ))
_sym_db.RegisterMessage(RpcRsp)


# @@protoc_insertion_point(module_scope)
